Lol Message Blog
trycourier/community-projects pull request #1
Opened 2022-10-12 04:29 UTC by n4ze3m

2022-10-12 21:24 UTC, shreythecray requested changes
This is amazing, Nazeem! I've added some comments. Once you have resolved them all, I'll take it from there and make some edits before merging.

2022-10-12 21:24 UTC, shreythecray commented on lol_message/blog.md
> +# Lol Message
Great job, Nazeem!

2022-10-12 21:24 UTC, shreythecray commented on lol_message/blog.md
> +During the [Courier Hack](https://courier-hacks.devpost.com/), I wanted to build a project that was fun and easy to use. So I decided to build an open source `NGL.link` alternative with email notific
Here are some suggestions to add to your introduction:
- what is NGL.link and why is that a good example to follow?
- what is the value of making this project open source?
- why did you choose email notifications over other channels?
- what are the capabilities of this application?

I would also recommend embedding or adding a link to your demo video here, and linking your DevPost page in the Quick Links section below.

2022-10-12 21:24 UTC, shreythecray commented on lol_message/blog.md
> +## Instructions
- Are there any pre-reqs to building this project?
- Are there are skills that the user should have to successfully complete this or can people with little-no experience complete it?

2022-10-12 21:24 UTC, shreythecray commented on lol_message/blog.md
> +We will be building core features of the project in this tutorial. You can find the source code of the full project [here](https://github.com/n4ze3m/lol), and you can find the live demo [here](https:
Love this!

2022-10-12 21:24 UTC, shreythecray commented on lol_message/blog.md
> +![Architecture Diagram](https://i.imgur.com/WtTIASB.png)
This is fantastic! You should explain this diagram in writing for increased accessibility.

2022-10-12 21:24 UTC, shreythecray commented on lol_message/blog.md
> +generator client {
I'd recommend breaking this down into four code snippets and explanations for each of them:

- generator client
- datasource db
- model user
- model message

2022-10-12 21:24 UTC, shreythecray commented on lol_message/blog.md
> +```ts
Let's break this down too. It can be a lot for someone who has never done this before.

2022-10-14 05:24 UTC, n4ze3m commented on lol_message/blog.md
> +# Lol Message
Thanks

2022-11-18 23:11 UTC, merged