Draft 1
trycourier/community-projects pull request #16
Opened 2023-02-27 00:30 UTC by arncv

Powernap Draft 1

2023-03-09 20:36 UTC, shreythecray requested changes
This blog looks great but there are some structural changes that need to be made (to bring back the deleted files). I've also added some comments to the blog directly.

2023-03-09 20:36 UTC, shreythecray commented on PowerNap/blog.md
> +PowerNap is a simple and elegant time tracker web application that allows users to set up a timer for their power nap sessions. The application was built to help individuals improve their productivit
Link "Courier API" to https://courier.com/

2023-03-09 20:36 UTC, shreythecray commented on PowerNap/blog.md
> +I chose to use Node.js for its efficient and lightweight nature, which makes it perfect for building scalable applications.For the frontend, I chose to use vanilla JavaScript because it's lightweight
Great introduction! In the first paragraph you refer to yourself as "we" and in the second one you use "I". I'd recommend sticking to one person, so either write as "I did this" or "we did this".

2023-03-09 20:36 UTC, shreythecray commented on PowerNap/blog.md
> +   ```javascript
Thanks for breaking down the code!

2023-03-09 20:36 UTC, shreythecray commented on PowerNap/blog.md
> +# Boost Your Productivity with PowerNap - A Time Tracker Web App Integrated with Courier API for Effortless Notification Management.
This file should be titled readme.md

2023-03-09 20:36 UTC, shreythecray commented on PowerNap/blog.md
> +   PowerNap includes a menu with buttons for setting the timer length and selecting the type of session, as well as a progress bar that displays the remaining time. The timer is contained within a ci
Add new line

2023-03-11 09:10 UTC, arncv commented
I've made the changes requested in another Pull Request and also rectified some of the structural errors of this Pull Request

Link to PR - https://github.com/trycourier/community-projects/pull/17

2023-04-16 19:12 UTC, closed without merging