Create blog.md
trycourier/community-projects pull request #7
Opened 2022-11-09 20:32 UTC by devmrfitz

2022-11-10 18:57 UTC, shreythecray requested changes
Cool project!

2022-11-10 18:57 UTC, shreythecray commented on media-master/blog.md
> +Currently, to process any image or video, the server’s need to process them while they are being uploaded. This takes a lot of processing power and memory and eventually slows down the uploading proc
Cool project! You need to add some more context in the beginning for the reader to understand why this is important. Why are we looking at processing images and videos? Why does it matter that it take time - who does that impact and why is that bad? Including examples or analogies would help.

I'd also recommend adding either screenshots/gifs or embedding your demo video at the top.

2022-11-10 18:57 UTC, shreythecray commented on media-master/blog.md
> +- Azure Functions: Azure Functions is the ideal tool for asynchronous background tasks like ours.
Need more context on this

2022-11-10 18:57 UTC, shreythecray commented on media-master/blog.md
> +- Storing the files
Maybe number these?

2022-11-10 18:57 UTC, shreythecray commented on media-master/blog.md
> +```
Breakdown the code

2022-11-10 18:57 UTC, shreythecray commented on media-master/blog.md
> +So, our fast, light-weight and easy-to-use media processing service is ready to used and can help a lot of students and professionals in their day-to-day hustle.
Love it!

2022-11-16 03:24 UTC, devmrfitz commented on media-master/blog.md
> +Currently, to process any image or video, the server’s need to process them while they are being uploaded. This takes a lot of processing power and memory and eventually slows down the uploading proc
Done

2022-11-16 03:25 UTC, devmrfitz commented on media-master/blog.md
> +So, our fast, light-weight and easy-to-use media processing service is ready to used and can help a lot of students and professionals in their day-to-day hustle.
Thanks a lot!

2022-11-16 03:26 UTC, devmrfitz commented on media-master/blog.md
> +```
Done

2022-11-16 03:27 UTC, devmrfitz commented
@shreythecray Resolved all suggestions. Does it look good now?

2022-12-02 04:06 UTC, shreythecray approved these changes

2022-12-02 04:14 UTC, merged